export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const POSTS_LIKE_ERROR = 'POSTS_LIKE_ERROR';
export const POSTS_LIKE_SUCCESS = 'POSTS_LIKE_SUCCESS';