export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';

export const POST_LIKE_ERROR = 'POST_LIKE_ERROR';
export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS';